import React, { useState, useEffect, useMemo } from "react";
import { 
  Database, 
  RefreshCw, 
  CheckCircle2, 
  AlertCircle, 
  Package, 
  ShoppingBag, 
  Copy, 
  Check, 
  Plus, 
  Minus, 
  Layers,
  X,
  Lock,
  Unlock,
  KeyRound,
  ShieldCheck,
  TrendingUp,
  DollarSign,
  FileSpreadsheet,
  Search,
  Filter,
  BarChart3,
  Download,
  LogOut,
  Calendar,
  Sparkles,
  ChevronRight
} from "lucide-react";
import { MenuItem, DbOrder } from "../types";
import { 
  isSupabaseConfigured, 
  fetchProductsFromSupabase, 
  seedProductsToSupabase, 
  updateSupabaseStock, 
  fetchSupabaseOrders 
} from "../lib/supabase";

interface AdminDashboardProps {
  isOpen: boolean;
  onClose: () => void;
  menuItems: MenuItem[];
  onRefreshMenu: () => void;
  formatIDR: (price: number) => string;
}

export const AdminDashboard: React.FC<AdminDashboardProps> = ({
  isOpen,
  onClose,
  menuItems,
  onRefreshMenu,
  formatIDR,
}) => {
  const [activeTab, setActiveTab] = useState<"overview" | "stock" | "orders" | "sql" | "settings">("overview");
  const [isSeeding, setIsSeeding] = useState(false);
  const [seedMessage, setSeedMessage] = useState<string | null>(null);
  const [orders, setOrders] = useState<(DbOrder & { items?: any[] })[]>([]);
  const [isLoadingOrders, setIsLoadingOrders] = useState(false);
  const [updatingStockId, setUpdatingStockId] = useState<number | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);

  // Search & Filter state for Orders
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");

  // Admin Authentication State
  const [isAdminAuth, setIsAdminAuth] = useState<boolean>(() => {
    return sessionStorage.getItem("mam_admin_auth") === "true";
  });
  const [inputPin, setInputPin] = useState<string>("");
  const [pinError, setPinError] = useState<string | null>(null);
  const [storedPin, setStoredPin] = useState<string>(() => {
    return localStorage.getItem("mam_admin_pin") || "1234";
  });
  const [isChangingPin, setIsChangingPin] = useState<boolean>(false);
  const [newPinInput, setNewPinInput] = useState<string>("");

  const sqlSchema = `-- 1. Tabel Produk / Menu Catering
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Pesanan / Transactions
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY, -- ID transaksi unik dari Midtrans / MAM Order
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, settlement, cancel, expire
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Detail Pesanan (Item yang dibeli)
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INT NOT NULL,
  price NUMERIC NOT NULL
);`;

  useEffect(() => {
    if (isOpen && isAdminAuth) {
      loadOrders();
    }
  }, [isOpen, isAdminAuth]);

  const handleVerifyPin = (e: React.FormEvent) => {
    e.preventDefault();
    if (inputPin.trim() === storedPin) {
      setIsAdminAuth(true);
      sessionStorage.setItem("mam_admin_auth", "true");
      setPinError(null);
      setInputPin("");
    } else {
      setPinError("PIN Admin salah! (Default PIN: 1234)");
    }
  };

  const handleLogoutAdmin = () => {
    setIsAdminAuth(false);
    sessionStorage.removeItem("mam_admin_auth");
  };

  const handleChangePinSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newPinInput.trim().length >= 4) {
      localStorage.setItem("mam_admin_pin", newPinInput.trim());
      setStoredPin(newPinInput.trim());
      setIsChangingPin(false);
      setNewPinInput("");
      alert("PIN Admin berhasil diperbarui!");
    } else {
      alert("PIN harus minimal 4 digit.");
    }
  };

  const loadOrders = async () => {
    setIsLoadingOrders(true);
    const { data } = await fetchSupabaseOrders();
    if (data) {
      setOrders(data);
    }
    setIsLoadingOrders(false);
  };

  const handleSeed = async () => {
    setIsSeeding(true);
    setSeedMessage(null);
    const result = await seedProductsToSupabase(menuItems);
    setSeedMessage(result.message);
    setIsSeeding(false);
    onRefreshMenu();
  };

  const handleStockChange = async (item: MenuItem, delta: number) => {
    const currentStock = item.stock ?? 50;
    const newStock = Math.max(0, currentStock + delta);
    setUpdatingStockId(item.id);
    await updateSupabaseStock(item.id, newStock);
    setUpdatingStockId(null);
    onRefreshMenu();
  };

  const copySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  // Financial Statistics Calculation
  const stats = useMemo(() => {
    let totalRevenue = 0;
    let todayRevenue = 0;
    let countSettlement = 0;
    let countPending = 0;
    let countCanceled = 0;

    const todayStr = new Date().toISOString().split("T")[0];

    orders.forEach((ord) => {
      const isPaid = ord.status === "settlement" || ord.status === "success" || ord.status === "lunas";
      const amount = Number(ord.total_amount) || 0;

      if (isPaid) {
        totalRevenue += amount;
        countSettlement += 1;

        if (ord.created_at && ord.created_at.startsWith(todayStr)) {
          todayRevenue += amount;
        }
      } else if (ord.status === "pending") {
        countPending += 1;
      } else {
        countCanceled += 1;
      }
    });

    return {
      totalOrders: orders.length,
      totalRevenue,
      todayRevenue,
      countSettlement,
      countPending,
      countCanceled
    };
  }, [orders]);

  // Filtered Orders
  const filteredOrders = useMemo(() => {
    return orders.filter((ord) => {
      const matchesSearch =
        ord.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        ord.customer_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        ord.customer_phone.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesStatus =
        statusFilter === "all" ||
        (statusFilter === "paid" && (ord.status === "settlement" || ord.status === "success" || ord.status === "lunas")) ||
        (statusFilter === "pending" && ord.status === "pending") ||
        (statusFilter === "cancel" && (ord.status === "cancel" || ord.status === "expire" || ord.status === "deny"));

      return matchesSearch && matchesStatus;
    });
  }, [orders, searchQuery, statusFilter]);

  // CSV Accounting Export
  const exportOrdersCSV = () => {
    if (orders.length === 0) {
      alert("Belum ada data transaksi untuk diekspor.");
      return;
    }

    const headers = ["ID Transaksi", "Nama Pelanggan", "No. Telepon", "Total (Rp)", "Status", "Tanggal Transaksi"];
    const rows = orders.map((ord) => [
      `"${ord.id}"`,
      `"${ord.customer_name.replace(/"/g, '""')}"`,
      `"${ord.customer_phone.replace(/"/g, '""')}"`,
      ord.total_amount,
      `"${ord.status}"`,
      `"${ord.created_at ? new Date(ord.created_at).toLocaleString("id-ID") : ""}"`
    ]);

    const csvContent = "data:text/csv;charset=utf-8," + [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `laporan_pembukuan_mam_${new Date().toISOString().split("T")[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/70 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl shadow-2xl max-w-4xl w-full max-h-[92vh] flex flex-col overflow-hidden border border-outline-variant/20">
        
        {/* Header */}
        <div className="p-5 sm:p-6 bg-gradient-to-r from-espresso-dark via-espresso to-espresso-dark text-white flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-amber-500/20 text-amber-400 rounded-2xl border border-amber-500/30">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-black tracking-tight">Admin Dashboard & Pembukuan MAM</h3>
                {isSupabaseConfigured ? (
                  <span className="inline-flex items-center gap-1 text-[11px] px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 font-semibold">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                    Live Supabase
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 text-[11px] px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 font-semibold">
                    <AlertCircle className="w-3.5 h-3.5" />
                    Demo Mode (Lokal)
                  </span>
                )}
              </div>
              <p className="text-xs text-white/70 mt-0.5">
                Portal Pengelola: Keuangan, Stok Supabase, Transaksi & Laporan Pembukuan.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {isAdminAuth && (
              <button
                onClick={handleLogoutAdmin}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition-all border border-white/20 cursor-pointer"
                title="Kunci Akses Admin"
              >
                <Lock className="w-3.5 h-3.5 text-amber-400" />
                <span className="hidden sm:inline">Kunci Admin</span>
              </button>
            )}
            <button
              onClick={onClose}
              className="p-2 rounded-full text-white/70 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {!isAdminAuth ? (
          /* PIN Verification Lock Screen */
          <div className="p-8 sm:p-12 flex flex-col items-center justify-center text-center my-auto space-y-6">
            <div className="p-5 bg-terracotta/10 text-terracotta rounded-3xl border border-terracotta/20 shadow-xs">
              <Lock className="w-12 h-12" />
            </div>
            
            <div className="max-w-sm space-y-2">
              <h4 className="text-2xl font-black text-espresso-dark">Area Terproteksi Admin</h4>
              <p className="text-xs text-espresso-dark/70 leading-relaxed">
                Halaman ini hanya dapat diakses oleh pemilik / pengelola MAM Catering. Masukkan PIN Admin untuk melanjutkan.
              </p>
            </div>

            <form onSubmit={handleVerifyPin} className="w-full max-w-xs space-y-3">
              <div className="relative">
                <KeyRound className="w-4 h-4 absolute left-3.5 top-3.5 text-espresso-dark/40" />
                <input
                  type="password"
                  maxLength={10}
                  value={inputPin}
                  onChange={(e) => setInputPin(e.target.value)}
                  placeholder="Masukkan PIN Admin..."
                  className="w-full pl-10 pr-4 py-3 rounded-2xl border border-outline-variant/30 text-sm focus:outline-none focus:border-terracotta focus:ring-2 focus:ring-terracotta/20 text-center font-mono tracking-widest text-espresso-dark bg-warm-cream/30 font-bold"
                  autoFocus
                />
              </div>

              {pinError && (
                <p className="text-xs text-red-600 font-semibold bg-red-50 p-2.5 rounded-xl border border-red-200">
                  {pinError}
                </p>
              )}

              <button
                type="submit"
                className="w-full py-3 rounded-2xl bg-terracotta text-white font-bold text-sm hover:bg-terracotta-dark transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer"
              >
                <Unlock className="w-4 h-4" />
                Masuk ke Dashboard
              </button>

              <div className="pt-2 text-xs text-espresso-dark/50 flex items-center justify-center gap-1.5">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                <span>PIN Default: </span>
                <code className="bg-warm-cream px-2 py-0.5 rounded border border-outline-variant/20 font-bold text-espresso-dark">1234</code>
              </div>
            </form>
          </div>
        ) : (
          /* Main Authenticated Dashboard */
          <>
            {/* Navigation Tabs */}
            <div className="flex border-b border-outline-variant/15 bg-warm-cream/30 px-4 sm:px-6 pt-2 gap-1 sm:gap-2 items-center justify-between overflow-x-auto shrink-0">
              <div className="flex gap-1 sm:gap-2">
                <button
                  onClick={() => setActiveTab("overview")}
                  className={`flex items-center gap-2 px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-bold border-b-2 transition-all cursor-pointer whitespace-nowrap ${
                    activeTab === "overview"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <BarChart3 className="w-4 h-4" />
                  Ringkasan Keuangan
                </button>
                <button
                  onClick={() => setActiveTab("stock")}
                  className={`flex items-center gap-2 px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-bold border-b-2 transition-all cursor-pointer whitespace-nowrap ${
                    activeTab === "stock"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <Package className="w-4 h-4" />
                  Stok Menu Supabase
                </button>
                <button
                  onClick={() => setActiveTab("orders")}
                  className={`flex items-center gap-2 px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-bold border-b-2 transition-all cursor-pointer whitespace-nowrap ${
                    activeTab === "orders"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <ShoppingBag className="w-4 h-4" />
                  Daftar Transaksi ({orders.length})
                </button>
                <button
                  onClick={() => setActiveTab("sql")}
                  className={`flex items-center gap-2 px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-bold border-b-2 transition-all cursor-pointer whitespace-nowrap ${
                    activeTab === "sql"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <Layers className="w-4 h-4" />
                  SQL Schema
                </button>
              </div>

              <button
                onClick={() => setIsChangingPin(!isChangingPin)}
                className="text-xs text-espresso-dark/60 hover:text-espresso-dark font-semibold underline flex items-center gap-1 pr-2 cursor-pointer shrink-0"
              >
                <KeyRound className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">{isChangingPin ? "Batal" : "Ganti PIN"}</span>
              </button>
            </div>

            {/* Change PIN Box if toggled */}
            {isChangingPin && (
              <div className="p-4 mx-6 mt-3 bg-warm-cream/70 rounded-2xl border border-outline-variant/20 flex flex-col sm:flex-row items-start sm:items-center justify-between text-xs gap-3 shrink-0">
                <div>
                  <span className="font-bold text-espresso-dark block">Ubah PIN Admin</span>
                  <span className="text-espresso-dark/60">PIN saat ini: <code className="font-mono font-bold">{storedPin}</code></span>
                </div>
                <form onSubmit={handleChangePinSubmit} className="flex items-center gap-2 w-full sm:w-auto">
                  <input
                    type="password"
                    maxLength={10}
                    placeholder="PIN Baru..."
                    value={newPinInput}
                    onChange={(e) => setNewPinInput(e.target.value)}
                    className="px-3 py-1.5 rounded-xl border border-outline-variant/30 text-xs font-mono w-full sm:w-28 bg-white focus:outline-none focus:border-terracotta"
                  />
                  <button
                    type="submit"
                    className="px-3.5 py-1.5 rounded-xl bg-terracotta text-white font-bold text-xs hover:bg-terracotta-dark transition-all shrink-0 cursor-pointer"
                  >
                    Simpan PIN
                  </button>
                </form>
              </div>
            )}

            {/* Body Content */}
            <div className="p-5 sm:p-6 overflow-y-auto flex-1 space-y-5">

              {/* TAB 1: RINGKASAN KEUANGAN & PEMBUKUAN */}
              {activeTab === "overview" && (
                <div className="space-y-5">
                  
                  {/* Financial KPI Cards Grid */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="p-5 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-700 text-white shadow-md relative overflow-hidden">
                      <div className="absolute -right-4 -bottom-4 opacity-15">
                        <DollarSign className="w-28 h-28" />
                      </div>
                      <span className="text-xs font-semibold uppercase tracking-wider text-emerald-100 block mb-1">
                        Total Omset / Lunas
                      </span>
                      <h4 className="text-2xl sm:text-3xl font-black">
                        {formatIDR(stats.totalRevenue)}
                      </h4>
                      <p className="text-[11px] text-emerald-100 mt-2 flex items-center gap-1">
                        <TrendingUp className="w-3.5 h-3.5" />
                        <span>{stats.countSettlement} transaksi lunas tercatat</span>
                      </p>
                    </div>

                    <div className="p-5 rounded-2xl bg-gradient-to-br from-terracotta to-amber-700 text-white shadow-md relative overflow-hidden">
                      <div className="absolute -right-4 -bottom-4 opacity-15">
                        <Calendar className="w-28 h-28" />
                      </div>
                      <span className="text-xs font-semibold uppercase tracking-wider text-amber-100 block mb-1">
                        Pendapatan Hari Ini
                      </span>
                      <h4 className="text-2xl sm:text-3xl font-black">
                        {formatIDR(stats.todayRevenue)}
                      </h4>
                      <p className="text-[11px] text-amber-100 mt-2">
                        Pemesanan masuk tanggal hari ini
                      </p>
                    </div>

                    <div className="p-5 rounded-2xl bg-gradient-to-br from-espresso-dark to-espresso text-white shadow-md relative overflow-hidden">
                      <div className="absolute -right-4 -bottom-4 opacity-15">
                        <ShoppingBag className="w-28 h-28" />
                      </div>
                      <span className="text-xs font-semibold uppercase tracking-wider text-white/70 block mb-1">
                        Total Pesanan Masuk
                      </span>
                      <h4 className="text-2xl sm:text-3xl font-black">
                        {stats.totalOrders} <span className="text-sm font-normal text-white/60">Order</span>
                      </h4>
                      <div className="flex items-center gap-3 text-[11px] text-white/80 mt-2">
                        <span className="text-emerald-400 font-bold">{stats.countSettlement} Lunas</span>
                        <span>•</span>
                        <span className="text-amber-400 font-bold">{stats.countPending} Pending</span>
                      </div>
                    </div>
                  </div>

                  {/* Quick Export & Actions Bar */}
                  <div className="p-4 bg-warm-cream/50 rounded-2xl border border-outline-variant/15 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                    <div>
                      <h4 className="text-sm font-bold text-espresso-dark flex items-center gap-2">
                        <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
                        Ekspor Laporan Pembukuan (Excel / CSV)
                      </h4>
                      <p className="text-xs text-espresso-dark/60 mt-0.5">
                        Unduh seluruh riwayat transaksi pelanggan dari Supabase dalam format CSV untuk rekonsiliasi kas.
                      </p>
                    </div>
                    <button
                      onClick={exportOrdersCSV}
                      className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center gap-2 transition-all shadow-sm shrink-0 cursor-pointer"
                    >
                      <Download className="w-4 h-4" />
                      Unduh CSV Pembukuan
                    </button>
                  </div>

                  {/* Stock Overview Summary */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-espresso-dark/60">
                        Ringkasan Stok Produk Catering
                      </h4>
                      <button
                        onClick={() => setActiveTab("stock")}
                        className="text-xs text-terracotta font-bold hover:underline flex items-center gap-1 cursor-pointer"
                      >
                        Kelola Stok Lengkap
                        <ChevronRight className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                      {menuItems.slice(0, 4).map((item) => {
                        const stockVal = item.stock ?? 50;
                        const isOut = stockVal <= 0;
                        return (
                          <div key={item.id} className="p-3.5 bg-white rounded-2xl border border-outline-variant/20 shadow-2xs space-y-2">
                            <div className="flex items-center gap-2.5">
                              <img src={item.image} alt={item.name} className="w-8 h-8 rounded-lg object-cover" />
                              <div className="overflow-hidden">
                                <h5 className="text-xs font-bold text-espresso-dark truncate">{item.name}</h5>
                                <span className="text-[10px] text-espresso-dark/60 block">{formatIDR(item.price)}</span>
                              </div>
                            </div>
                            <div className="flex items-center justify-between pt-1 border-t border-outline-variant/10 text-xs">
                              <span className="text-[11px] text-espresso-dark/50">Sisa Stok:</span>
                              <span className={`font-bold px-2 py-0.5 rounded-full text-[10px] ${
                                isOut ? "bg-red-100 text-red-700" : stockVal < 10 ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"
                              }`}>
                                {isOut ? "Habis" : `${stockVal} unit`}
                              </span>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                </div>
              )}

              {/* TAB 2: KELOLA STOK MENU SUPABASE */}
              {activeTab === "stock" && (
                <div className="space-y-4">
                  {!isSupabaseConfigured && (
                    <div className="p-4 bg-amber-50 border border-amber-200 rounded-2xl flex items-start gap-3 text-amber-900 text-xs leading-relaxed">
                      <AlertCircle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                      <div>
                        <span className="font-bold block mb-0.5 text-sm">Supabase Environment Variable Belum Diisi</span>
                        Tambahkan <code className="bg-amber-100 px-1 py-0.5 rounded text-amber-900 font-mono">VITE_SUPABASE_URL</code> dan <code className="bg-amber-100 px-1 py-0.5 rounded text-amber-900 font-mono">VITE_SUPABASE_ANON_KEY</code> pada file <code className="bg-amber-100 px-1 py-0.5 rounded font-mono">.env</code> untuk menghubungkan ke database live Supabase Anda.
                      </div>
                    </div>
                  )}

                  <div className="flex items-center justify-between bg-warm-cream/50 p-4 rounded-2xl border border-outline-variant/15 flex-col sm:flex-row gap-3">
                    <div>
                      <h4 className="text-sm font-bold text-espresso-dark">Sinkronisasi Database Supabase</h4>
                      <p className="text-xs text-espresso-dark/60">
                        Masukkan/Perbarui daftar menu awal beserta stok ke tabel <code className="font-mono bg-white px-1 rounded border">products</code>
                      </p>
                    </div>
                    <button
                      onClick={handleSeed}
                      disabled={isSeeding}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-terracotta text-white font-semibold text-xs hover:bg-terracotta-dark disabled:opacity-50 transition-all shadow-sm shrink-0 cursor-pointer"
                    >
                      <RefreshCw className={`w-3.5 h-3.5 ${isSeeding ? "animate-spin" : ""}`} />
                      {isSeeding ? "Memproses..." : "Sync / Seed ke Supabase"}
                    </button>
                  </div>

                  {seedMessage && (
                    <div
                      className={`p-3.5 rounded-xl text-xs font-medium border flex items-start justify-between gap-3 ${
                        seedMessage.toLowerCase().includes("gagal") || seedMessage.toLowerCase().includes("error") || seedMessage.toLowerCase().includes("belum")
                          ? "bg-red-50 text-red-900 border-red-200"
                          : "bg-emerald-50 text-emerald-900 border-emerald-200"
                      }`}
                    >
                      <div className="flex items-start gap-2">
                        {seedMessage.toLowerCase().includes("gagal") || seedMessage.toLowerCase().includes("error") || seedMessage.toLowerCase().includes("belum") ? (
                          <AlertCircle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                        ) : (
                          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                        )}
                        <div className="leading-relaxed">{seedMessage}</div>
                      </div>
                      {(seedMessage.includes("SQL") || seedMessage.includes("products")) && (
                        <button
                          onClick={() => setActiveTab("sql")}
                          className="px-2.5 py-1 bg-terracotta text-white font-bold rounded-lg text-[11px] hover:bg-terracotta-dark shrink-0 transition-colors shadow-xs cursor-pointer"
                        >
                          Buka SQL Schema
                        </button>
                      )}
                    </div>
                  )}

                  <div className="space-y-2">
                    <h4 className="text-xs font-bold uppercase tracking-wider text-espresso-dark/60">
                      Daftar Stok Menu Terbaru ({menuItems.length} Item)
                    </h4>

                    <div className="divide-y divide-outline-variant/15 border border-outline-variant/20 rounded-2xl overflow-hidden bg-white">
                      {menuItems.map((item) => {
                        const currentStock = item.stock ?? 50;
                        const isOut = currentStock <= 0;

                        return (
                          <div key={item.id} className="p-3.5 flex flex-col sm:flex-row items-start sm:items-center justify-between hover:bg-warm-cream/20 transition-colors gap-3">
                            <div className="flex items-center gap-3">
                              <img 
                                src={item.image} 
                                alt={item.name} 
                                className="w-12 h-12 rounded-xl object-cover border border-outline-variant/20 shrink-0"
                              />
                              <div>
                                <h5 className="text-sm font-bold text-espresso-dark">{item.name}</h5>
                                <span className="text-xs text-espresso-dark/60">{formatIDR(item.price)}</span>
                              </div>
                            </div>

                            <div className="flex items-center justify-between sm:justify-end w-full sm:w-auto gap-3">
                              <span
                                className={`text-xs px-2.5 py-1 rounded-full font-bold ${
                                  isOut 
                                    ? "bg-red-100 text-red-700 border border-red-200" 
                                    : currentStock < 10 
                                    ? "bg-amber-100 text-amber-800 border border-amber-200" 
                                    : "bg-emerald-100 text-emerald-800 border border-emerald-200"
                                }`}
                              >
                                {isOut ? "Stok Habis" : `Stok: ${currentStock}`}
                              </span>

                              <div className="flex items-center gap-1 bg-warm-cream/60 p-1 rounded-xl border border-outline-variant/20">
                                <button
                                  onClick={() => handleStockChange(item, -5)}
                                  disabled={updatingStockId === item.id}
                                  className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark text-xs font-bold px-2 transition-colors disabled:opacity-50 cursor-pointer"
                                  title="Kurangi 5"
                                >
                                  -5
                                </button>
                                <button
                                  onClick={() => handleStockChange(item, -1)}
                                  disabled={updatingStockId === item.id}
                                  className="p-1.5 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark transition-colors disabled:opacity-50 cursor-pointer"
                                  title="Kurangi 1"
                                >
                                  <Minus className="w-3.5 h-3.5" />
                                </button>
                                <span className="w-8 text-center text-xs font-bold text-espresso-dark">
                                  {updatingStockId === item.id ? "..." : currentStock}
                                </span>
                                <button
                                  onClick={() => handleStockChange(item, 1)}
                                  disabled={updatingStockId === item.id}
                                  className="p-1.5 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark transition-colors disabled:opacity-50 cursor-pointer"
                                  title="Tambah 1"
                                >
                                  <Plus className="w-3.5 h-3.5" />
                                </button>
                                <button
                                  onClick={() => handleStockChange(item, 10)}
                                  disabled={updatingStockId === item.id}
                                  className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark text-xs font-bold px-2 transition-colors disabled:opacity-50 cursor-pointer"
                                  title="Tambah 10"
                                >
                                  +10
                                </button>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 3: DAFTAR TRANSAKSI & PEMBUKUAN */}
              {activeTab === "orders" && (
                <div className="space-y-4">
                  
                  {/* Search and Filters */}
                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-warm-cream/40 p-3 rounded-2xl border border-outline-variant/15">
                    <div className="relative flex-1">
                      <Search className="w-4 h-4 absolute left-3 top-3 text-espresso-dark/40" />
                      <input
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Cari ID Transaksi / Nama Pelanggan..."
                        className="w-full pl-9 pr-4 py-2 rounded-xl bg-white border border-outline-variant/20 text-xs focus:outline-none focus:border-terracotta"
                      />
                    </div>

                    <div className="flex items-center gap-2">
                      <select
                        value={statusFilter}
                        onChange={(e) => setStatusFilter(e.target.value)}
                        className="px-3 py-2 rounded-xl bg-white border border-outline-variant/20 text-xs font-semibold text-espresso-dark focus:outline-none cursor-pointer"
                      >
                        <option value="all">Semua Status</option>
                        <option value="paid">Lunas (Settlement)</option>
                        <option value="pending">Pending</option>
                        <option value="cancel">Batal / Expire</option>
                      </select>

                      <button
                        onClick={loadOrders}
                        disabled={isLoadingOrders}
                        className="p-2 rounded-xl bg-white border border-outline-variant/20 text-espresso-dark hover:bg-warm-cream transition-all shrink-0 cursor-pointer"
                        title="Refresh Data"
                      >
                        <RefreshCw className={`w-4 h-4 ${isLoadingOrders ? "animate-spin" : ""}`} />
                      </button>

                      <button
                        onClick={exportOrdersCSV}
                        className="px-3 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center gap-1.5 transition-all shadow-xs shrink-0 cursor-pointer"
                        title="Unduh CSV Pembukuan"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span className="hidden sm:inline">CSV</span>
                      </button>
                    </div>
                  </div>

                  {isLoadingOrders ? (
                    <div className="text-center py-12 text-espresso-dark/50 text-xs">
                      <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-terracotta" />
                      Memuat data pesanan dari Supabase...
                    </div>
                  ) : filteredOrders.length === 0 ? (
                    <div className="text-center py-12 border border-dashed border-outline-variant/30 rounded-2xl bg-warm-cream/20">
                      <ShoppingBag className="w-8 h-8 text-espresso-dark/30 mx-auto mb-2" />
                      <p className="text-xs font-bold text-espresso-dark/70">
                        {orders.length === 0 ? "Belum ada pesanan tercatat di Supabase" : "Tidak ada pesanan yang sesuai filter"}
                      </p>
                      <p className="text-[11px] text-espresso-dark/50 mt-1 max-w-sm mx-auto">
                        Pesanan baru dari Midtrans / Checkout akan langsung tercatat di tabel orders Supabase.
                      </p>
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {filteredOrders.map((ord) => {
                        const isSettled = ord.status === "settlement" || ord.status === "success" || ord.status === "lunas";
                        const isPending = ord.status === "pending";

                        return (
                          <div key={ord.id} className="p-4 border border-outline-variant/20 rounded-2xl bg-white shadow-2xs space-y-2">
                            <div className="flex items-center justify-between text-xs border-b border-outline-variant/10 pb-2.5">
                              <div className="flex items-center gap-2">
                                <span className="font-mono font-bold text-terracotta bg-terracotta/5 px-2 py-0.5 rounded border border-terracotta/20">
                                  {ord.id}
                                </span>
                                <span className="text-espresso-dark/50 text-[11px]">
                                  {ord.created_at ? new Date(ord.created_at).toLocaleString("id-ID") : "Baru saja"}
                                </span>
                              </div>
                              <span className={`px-2.5 py-0.5 rounded-full font-bold uppercase text-[10px] ${
                                isSettled
                                  ? "bg-emerald-100 text-emerald-800 border border-emerald-200" 
                                  : isPending 
                                  ? "bg-amber-100 text-amber-800 border border-amber-200" 
                                  : "bg-gray-100 text-gray-700 border border-gray-200"
                              }`}>
                                {ord.status}
                              </span>
                            </div>

                            <div className="flex justify-between items-end pt-1">
                              <div>
                                <p className="text-sm font-bold text-espresso-dark">{ord.customer_name}</p>
                                <p className="text-xs text-espresso-dark/60 font-mono mt-0.5">{ord.customer_phone}</p>
                              </div>
                              <div className="text-right">
                                <span className="text-[10px] text-espresso-dark/50 block">Total Transaksi</span>
                                <span className="text-sm font-black text-terracotta">{formatIDR(Number(ord.total_amount))}</span>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              )}

              {/* TAB 4: SQL SCHEMA */}
              {activeTab === "sql" && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="text-sm font-bold text-espresso-dark">Struktur Tabel Supabase (SQL Script)</h4>
                      <p className="text-xs text-espresso-dark/60">
                        Jalankan skrip ini di <b>SQL Editor</b> pada dashboard Supabase Anda.
                      </p>
                    </div>
                    <button
                      onClick={copySql}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-terracotta text-white font-semibold text-xs hover:bg-terracotta-dark transition-all cursor-pointer"
                    >
                      {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                      {copiedSql ? "Tersalin!" : "Salin SQL"}
                    </button>
                  </div>

                  <div className="relative rounded-2xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800 leading-relaxed shadow-inner">
                    <pre>{sqlSchema}</pre>
                  </div>
                </div>
              )}

            </div>

            {/* Footer */}
            <div className="p-4 bg-warm-cream/40 border-t border-outline-variant/15 flex items-center justify-between text-xs text-espresso-dark/70 shrink-0">
              <span className="flex items-center gap-1.5 font-medium">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Integrasi Database Live Supabase & Pembukuan Kas
              </span>
              <button
                onClick={onClose}
                className="px-4 py-2 rounded-xl bg-espresso-dark text-white font-semibold hover:bg-espresso transition-colors cursor-pointer"
              >
                Tutup Dashboard
              </button>
            </div>
          </>
        )}

      </div>
    </div>
  );
};
