import React, { useState, useEffect } from "react";
import { 
  Database, 
  RefreshCw, 
  CheckCircle2, 
  AlertCircle, 
  Package, 
  ShoppingBag, 
  Copy, 
  Check, 
  Plus, 
  Minus, 
  Layers,
  X,
  Lock,
  Unlock,
  KeyRound,
  ShieldCheck
} from "lucide-react";
import { MenuItem, DbOrder } from "../types";
import { 
  isSupabaseConfigured, 
  supabase, 
  fetchProductsFromSupabase, 
  seedProductsToSupabase, 
  updateSupabaseStock, 
  fetchSupabaseOrders,
  fetchAdminPin,
  saveAdminPin
} from "../lib/supabase";

interface SupabaseManagerProps {
  isOpen: boolean;
  onClose: () => void;
  menuItems: MenuItem[];
  onRefreshMenu: () => void;
  formatIDR: (price: number) => string;
}

export const SupabaseManager: React.FC<SupabaseManagerProps> = ({
  isOpen,
  onClose,
  menuItems,
  onRefreshMenu,
  formatIDR,
}) => {
  const [activeTab, setActiveTab] = useState<"stock" | "orders" | "sql">("stock");
  const [isSeeding, setIsSeeding] = useState(false);
  const [seedMessage, setSeedMessage] = useState<string | null>(null);
  const [orders, setOrders] = useState<(DbOrder & { items?: any[] })[]>([]);
  const [isLoadingOrders, setIsLoadingOrders] = useState(false);
  const [updatingStockId, setUpdatingStockId] = useState<number | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);

  // Admin Authentication State
  const [isAdminAuth, setIsAdminAuth] = useState<boolean>(() => {
    return sessionStorage.getItem("mam_admin_auth") === "true";
  });
  const [inputPin, setInputPin] = useState<string>("");
  const [pinError, setPinError] = useState<string | null>(null);
  const [storedPin, setStoredPin] = useState<string>("1234");
  const [isVerifyingPin, setIsVerifyingPin] = useState<boolean>(false);
  const [isChangingPin, setIsChangingPin] = useState<boolean>(false);
  const [newPinInput, setNewPinInput] = useState<string>("");

  const sqlSchema = `-- 1. Tabel Produk / Menu Catering
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Pesanan / Transactions
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Detail Pesanan
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INT NOT NULL,
  price NUMERIC NOT NULL
);

-- 4. Tabel Pengaturan Admin (PENTING: Agar ganti PIN Admin tersimpan terpusat di Supabase)
CREATE TABLE IF NOT EXISTS admin_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO admin_settings (key, value) VALUES ('admin_pin', '1234') ON CONFLICT (key) DO NOTHING;`;

  useEffect(() => {
    if (isOpen) {
      fetchAdminPin().then((pin) => {
        if (pin) setStoredPin(pin);
      });
    }
  }, [isOpen]);

  useEffect(() => {
    if (isOpen && isAdminAuth && activeTab === "orders") {
      loadOrders();
    }
  }, [isOpen, isAdminAuth, activeTab]);

  const handleVerifyPin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputPin.trim()) return;

    setIsVerifyingPin(true);
    setPinError(null);

    try {
      // 1. Verify via Server API
      const res = await fetch("/api/admin/verify-pin", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pin: inputPin.trim() }),
      });

      if (res.ok) {
        const json = await res.json();
        if (json.verified || json.success) {
          setIsAdminAuth(true);
          sessionStorage.setItem("mam_admin_auth", "true");
          setPinError(null);
          setInputPin("");
          setIsVerifyingPin(false);
          return;
        }
      }

      if (res.status === 401) {
        setPinError("PIN Admin salah!");
        setIsVerifyingPin(false);
        return;
      }

      // 2. Direct Supabase Fallback
      const latestPin = await fetchAdminPin();
      const activePin = (latestPin && latestPin.length >= 4) ? latestPin : storedPin;
      setStoredPin(activePin);

      if (inputPin.trim() === activePin) {
        setIsAdminAuth(true);
        sessionStorage.setItem("mam_admin_auth", "true");
        setPinError(null);
        setInputPin("");
      } else {
        setPinError("PIN Admin salah!");
      }
    } catch (err) {
      const latestPin = await fetchAdminPin();
      if (inputPin.trim() === (latestPin || storedPin)) {
        setIsAdminAuth(true);
        sessionStorage.setItem("mam_admin_auth", "true");
        setPinError(null);
        setInputPin("");
      } else {
        setPinError("PIN Admin salah!");
      }
    } finally {
      setIsVerifyingPin(false);
    }
  };

  const handleLogoutAdmin = () => {
    setIsAdminAuth(false);
    sessionStorage.removeItem("mam_admin_auth");
  };

  const handleChangePinSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newPinInput.trim().length >= 4) {
      const pinVal = newPinInput.trim();
      await saveAdminPin(pinVal);
      setStoredPin(pinVal);
      setIsChangingPin(false);
      setNewPinInput("");
      alert("PIN Admin berhasil diperbarui dan tersimpan terpusat untuk semua perangkat!");
    } else {
      alert("PIN harus minimal 4 digit.");
    }
  };

  const loadOrders = async () => {
    setIsLoadingOrders(true);
    const { data } = await fetchSupabaseOrders();
    if (data) {
      setOrders(data);
    }
    setIsLoadingOrders(false);
  };

  const handleSeed = async () => {
    setIsSeeding(true);
    setSeedMessage(null);
    const result = await seedProductsToSupabase(menuItems);
    setSeedMessage(result.message);
    setIsSeeding(false);
    onRefreshMenu();
  };

  const handleStockChange = async (item: MenuItem, delta: number) => {
    const currentStock = item.stock ?? 50;
    const newStock = Math.max(0, currentStock + delta);
    setUpdatingStockId(item.id);
    await updateSupabaseStock(item.id, newStock);
    setUpdatingStockId(null);
    onRefreshMenu();
  };

  const copySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden border border-outline-variant/20">
        
        {/* Header */}
        <div className="p-6 bg-gradient-to-r from-espresso-dark via-espresso to-espresso-dark text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-emerald-500/20 text-emerald-400 rounded-2xl border border-emerald-500/30">
              <Database className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-bold">Integrasi Supabase & Stok</h3>
                {isSupabaseConfigured ? (
                  <span className="inline-flex items-center gap-1 text-xs px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 font-semibold">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                    Terhubung
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 text-xs px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 font-semibold">
                    <AlertCircle className="w-3 h-3" />
                    Demo Mode (Lokal)
                  </span>
                )}
              </div>
              <p className="text-xs text-white/70 mt-0.5">
                Kelola persediaan stok dan riwayat pesanan langsung terhubung ke tabel Supabase.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {isAdminAuth && (
              <button
                onClick={handleLogoutAdmin}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition-all border border-white/20"
                title="Kunci Akses Admin"
              >
                <Lock className="w-3.5 h-3.5 text-amber-400" />
                <span>Kunci Admin</span>
              </button>
            )}
            <button
              onClick={onClose}
              className="p-2 rounded-full text-white/70 hover:text-white hover:bg-white/10 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {!isAdminAuth ? (
          /* PIN Verification Lock Screen */
          <div className="p-8 flex flex-col items-center justify-center text-center my-auto space-y-6">
            <div className="p-4 bg-terracotta/10 text-terracotta rounded-3xl border border-terracotta/20 shadow-xs">
              <Lock className="w-10 h-10" />
            </div>
            
            <div className="max-w-sm space-y-1">
              <h4 className="text-xl font-bold text-espresso-dark">Area Terproteksi Admin</h4>
              <p className="text-xs text-espresso-dark/70 leading-relaxed">
                Fitur Kelola Stok & Database terbatas hanya untuk pengelola catering. Masukkan PIN Admin untuk melanjutkan.
              </p>
            </div>

            <form onSubmit={handleVerifyPin} className="w-full max-w-xs space-y-3">
              <div className="relative">
                <KeyRound className="w-4 h-4 absolute left-3.5 top-3.5 text-espresso-dark/40" />
                <input
                  type="password"
                  maxLength={10}
                  value={inputPin}
                  onChange={(e) => setInputPin(e.target.value)}
                  placeholder="Masukkan PIN Admin..."
                  className="w-full pl-10 pr-4 py-2.5 rounded-2xl border border-outline-variant/30 text-sm focus:outline-none focus:border-terracotta focus:ring-2 focus:ring-terracotta/20 text-center font-mono tracking-widest text-espresso-dark bg-warm-cream/30"
                  autoFocus
                />
              </div>

              {pinError && (
                <p className="text-xs text-red-600 font-semibold bg-red-50 p-2 rounded-xl border border-red-200">
                  {pinError}
                </p>
              )}

              <button
                type="submit"
                disabled={isVerifyingPin}
                className="w-full py-2.5 rounded-2xl bg-terracotta text-white font-bold text-sm hover:bg-terracotta-dark transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isVerifyingPin ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Memverifikasi...
                  </>
                ) : (
                  <>
                    <Unlock className="w-4 h-4" />
                    Buka Akses Admin
                  </>
                )}
              </button>

              <div className="pt-2 text-[11px] text-espresso-dark/50 flex items-center justify-center gap-1.5">
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
                <span>Terverifikasi Terpusat via Server & Supabase</span>
              </div>
            </form>
          </div>
        ) : (
          /* Main Authenticated Dashboard */
          <>
            {/* Navigation Tabs */}
            <div className="flex border-b border-outline-variant/15 bg-warm-cream/30 px-6 pt-2 gap-2 items-center justify-between">
              <div className="flex gap-2">
                <button
                  onClick={() => setActiveTab("stock")}
                  className={`flex items-center gap-2 px-4 py-2.5 text-sm font-semibold border-b-2 transition-all ${
                    activeTab === "stock"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <Package className="w-4 h-4" />
                  Kelola Stok Menu
                </button>
                <button
                  onClick={() => setActiveTab("orders")}
                  className={`flex items-center gap-2 px-4 py-2.5 text-sm font-semibold border-b-2 transition-all ${
                    activeTab === "orders"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <ShoppingBag className="w-4 h-4" />
                  Riwayat Pesanan
                </button>
                <button
                  onClick={() => setActiveTab("sql")}
                  className={`flex items-center gap-2 px-4 py-2.5 text-sm font-semibold border-b-2 transition-all ${
                    activeTab === "sql"
                      ? "border-terracotta text-terracotta bg-white rounded-t-xl shadow-xs"
                      : "border-transparent text-espresso-dark/60 hover:text-espresso-dark"
                  }`}
                >
                  <Layers className="w-4 h-4" />
                  SQL Schema
                </button>
              </div>

              {/* Change PIN button */}
              <button
                onClick={() => setIsChangingPin(!isChangingPin)}
                className="text-xs text-espresso-dark/60 hover:text-espresso-dark font-medium underline flex items-center gap-1 pr-2"
              >
                <KeyRound className="w-3.5 h-3.5" />
                {isChangingPin ? "Batal" : "Ganti PIN"}
              </button>
            </div>

            {/* Change PIN Box if toggled */}
            {isChangingPin && (
              <div className="p-4 mx-6 mt-4 bg-warm-cream/60 rounded-2xl border border-outline-variant/20 flex items-center justify-between text-xs">
                <div>
                  <span className="font-bold text-espresso-dark block">Ubah PIN Admin</span>
                  <span className="text-espresso-dark/60">PIN saat ini: <code className="font-mono font-bold">{storedPin}</code></span>
                </div>
                <form onSubmit={handleChangePinSubmit} className="flex items-center gap-2">
                  <input
                    type="password"
                    maxLength={10}
                    placeholder="PIN Baru..."
                    value={newPinInput}
                    onChange={(e) => setNewPinInput(e.target.value)}
                    className="px-3 py-1.5 rounded-xl border border-outline-variant/30 text-xs font-mono w-28 bg-white"
                  />
                  <button
                    type="submit"
                    className="px-3 py-1.5 rounded-xl bg-terracotta text-white font-bold text-xs hover:bg-terracotta-dark transition-all"
                  >
                    Simpan
                  </button>
                </form>
              </div>
            )}

        {/* Body Content */}
        <div className="p-6 overflow-y-auto flex-1 space-y-4">

          {/* TAB 1: KELOLA STOK */}
          {activeTab === "stock" && (
            <div className="space-y-4">
              {!isSupabaseConfigured && (
                <div className="p-4 bg-amber-50 border border-amber-200 rounded-2xl flex items-start gap-3 text-amber-900 text-xs leading-relaxed">
                  <AlertCircle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold block mb-0.5 text-sm">Supabase Environment Variable Belum Diisi</span>
                    Tambahkan <code className="bg-amber-100 px-1 py-0.5 rounded text-amber-900 font-mono">VITE_SUPABASE_URL</code> dan <code className="bg-amber-100 px-1 py-0.5 rounded text-amber-900 font-mono">VITE_SUPABASE_ANON_KEY</code> pada file <code className="bg-amber-100 px-1 py-0.5 rounded font-mono">.env</code> untuk menghubungkan ke database live Supabase Anda. Saat ini stok dapat disimulasikan secara interaktif di browser.
                  </div>
                </div>
              )}

              <div className="flex items-center justify-between bg-warm-cream/50 p-4 rounded-2xl border border-outline-variant/15">
                <div>
                  <h4 className="text-sm font-bold text-espresso-dark">Sinkronisasi Produk ke Supabase</h4>
                  <p className="text-xs text-espresso-dark/60">
                    Masukkan/Perbarui daftar menu awal beserta stok ke tabel <code className="font-mono bg-white px-1 rounded border">products</code>
                  </p>
                </div>
                <button
                  onClick={handleSeed}
                  disabled={isSeeding}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl bg-terracotta text-white font-semibold text-xs hover:bg-terracotta-dark disabled:opacity-50 transition-all shadow-sm shrink-0"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isSeeding ? "animate-spin" : ""}`} />
                  {isSeeding ? "Memproses..." : "Seed / Sync ke Supabase"}
                </button>
              </div>

              {seedMessage && (
                <div
                  className={`p-3.5 rounded-xl text-xs font-medium border flex items-start justify-between gap-3 ${
                    seedMessage.toLowerCase().includes("gagal") || seedMessage.toLowerCase().includes("error") || seedMessage.toLowerCase().includes("belum")
                      ? "bg-red-50 text-red-900 border-red-200"
                      : "bg-emerald-50 text-emerald-900 border-emerald-200"
                  }`}
                >
                  <div className="flex items-start gap-2">
                    {seedMessage.toLowerCase().includes("gagal") || seedMessage.toLowerCase().includes("error") || seedMessage.toLowerCase().includes("belum") ? (
                      <AlertCircle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                    ) : (
                      <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    )}
                    <div className="leading-relaxed">{seedMessage}</div>
                  </div>
                  {(seedMessage.includes("SQL") || seedMessage.includes("products")) && (
                    <button
                      onClick={() => setActiveTab("sql")}
                      className="px-2.5 py-1 bg-terracotta text-white font-bold rounded-lg text-[11px] hover:bg-terracotta-dark shrink-0 transition-colors shadow-xs"
                    >
                      Buka SQL Schema
                    </button>
                  )}
                </div>
              )}

              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-espresso-dark/60">
                  Daftar Stok Menu Terbaru ({menuItems.length} Item)
                </h4>

                <div className="divide-y divide-outline-variant/15 border border-outline-variant/20 rounded-2xl overflow-hidden bg-white">
                  {menuItems.map((item) => {
                    const currentStock = item.stock ?? 50;
                    const isOut = currentStock <= 0;

                    return (
                      <div key={item.id} className="p-3.5 flex items-center justify-between hover:bg-warm-cream/20 transition-colors">
                        <div className="flex items-center gap-3">
                          <img 
                            src={item.image} 
                            alt={item.name} 
                            className="w-10 h-10 rounded-xl object-cover border border-outline-variant/20"
                          />
                          <div>
                            <h5 className="text-sm font-bold text-espresso-dark">{item.name}</h5>
                            <span className="text-xs text-espresso-dark/60">{formatIDR(item.price)}</span>
                          </div>
                        </div>

                        <div className="flex items-center gap-3">
                          <span
                            className={`text-xs px-2.5 py-1 rounded-full font-bold ${
                              isOut 
                                ? "bg-red-100 text-red-700 border border-red-200" 
                                : currentStock < 10 
                                ? "bg-amber-100 text-amber-800 border border-amber-200" 
                                : "bg-emerald-100 text-emerald-800 border border-emerald-200"
                            }`}
                          >
                            {isOut ? "Stok Habis" : `Stok: ${currentStock}`}
                          </span>

                          <div className="flex items-center gap-1 bg-warm-cream/60 p-1 rounded-xl border border-outline-variant/20">
                            <button
                              onClick={() => handleStockChange(item, -5)}
                              disabled={updatingStockId === item.id}
                              className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark text-xs font-bold px-2 transition-colors disabled:opacity-50"
                              title="Kurangi 5"
                            >
                              -5
                            </button>
                            <button
                              onClick={() => handleStockChange(item, -1)}
                              disabled={updatingStockId === item.id}
                              className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark transition-colors disabled:opacity-50"
                              title="Kurangi 1"
                            >
                              <Minus className="w-3.5 h-3.5" />
                            </button>
                            <span className="w-8 text-center text-xs font-bold text-espresso-dark">
                              {updatingStockId === item.id ? "..." : currentStock}
                            </span>
                            <button
                              onClick={() => handleStockChange(item, 1)}
                              disabled={updatingStockId === item.id}
                              className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark transition-colors disabled:opacity-50"
                              title="Tambah 1"
                            >
                              <Plus className="w-3.5 h-3.5" />
                            </button>
                            <button
                              onClick={() => handleStockChange(item, 10)}
                              disabled={updatingStockId === item.id}
                              className="p-1 rounded-lg hover:bg-white text-espresso-dark/70 hover:text-espresso-dark text-xs font-bold px-2 transition-colors disabled:opacity-50"
                              title="Tambah 10"
                            >
                              +10
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: RIWAYAT PESANAN SUPABASE */}
          {activeTab === "orders" && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="text-sm font-bold text-espresso-dark">Pesanan Terbaru dari Supabase</h4>
                <button
                  onClick={loadOrders}
                  disabled={isLoadingOrders}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-warm-cream border border-outline-variant/20 text-xs font-semibold text-espresso-dark hover:bg-warm-cream/80 transition-all"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isLoadingOrders ? "animate-spin" : ""}`} />
                  Refresh Data
                </button>
              </div>

              {isLoadingOrders ? (
                <div className="text-center py-12 text-espresso-dark/50 text-xs">
                  <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-terracotta" />
                  Memuat data pesanan dari Supabase...
                </div>
              ) : orders.length === 0 ? (
                <div className="text-center py-12 border border-dashed border-outline-variant/30 rounded-2xl bg-warm-cream/20">
                  <ShoppingBag className="w-8 h-8 text-espresso-dark/30 mx-auto mb-2" />
                  <p className="text-xs font-bold text-espresso-dark/70">Belum ada pesanan tercatat di Supabase</p>
                  <p className="text-[11px] text-espresso-dark/50 mt-1 max-w-sm mx-auto">
                    Buat pesanan baru melalui menu pemesanan. Transaksi dan stock akan langsung tercatat secara otomatis!
                  </p>
                </div>
              ) : (
                <div className="space-y-3">
                  {orders.map((ord) => (
                    <div key={ord.id} className="p-4 border border-outline-variant/20 rounded-2xl bg-white shadow-2xs space-y-2">
                      <div className="flex items-center justify-between text-xs border-b border-outline-variant/10 pb-2">
                        <div>
                          <span className="font-mono font-bold text-terracotta">{ord.id}</span>
                          <span className="text-espresso-dark/50 text-[11px] ml-2">
                            {ord.created_at ? new Date(ord.created_at).toLocaleString("id-ID") : "Baru saja"}
                          </span>
                        </div>
                        <span className={`px-2.5 py-0.5 rounded-full font-bold uppercase text-[10px] ${
                          ord.status === "settlement" 
                            ? "bg-emerald-100 text-emerald-800" 
                            : ord.status === "pending" 
                            ? "bg-amber-100 text-amber-800" 
                            : "bg-gray-100 text-gray-700"
                        }`}>
                          {ord.status}
                        </span>
                      </div>

                      <div className="flex justify-between items-end pt-1">
                        <div>
                          <p className="text-sm font-bold text-espresso-dark">{ord.customer_name}</p>
                          <p className="text-xs text-espresso-dark/60">{ord.customer_phone}</p>
                        </div>
                        <div className="text-right">
                          <span className="text-[10px] text-espresso-dark/50 block">Total Transaksi</span>
                          <span className="text-sm font-bold text-terracotta">{formatIDR(Number(ord.total_amount))}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* TAB 3: SQL SCHEMA */}
          {activeTab === "sql" && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-bold text-espresso-dark">Struktur Tabel Supabase (SQL Script)</h4>
                  <p className="text-xs text-espresso-dark/60">
                    Jalankan skrip ini di <b>SQL Editor</b> pada dashboard Supabase Anda.
                  </p>
                </div>
                <button
                  onClick={copySql}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-terracotta text-white font-semibold text-xs hover:bg-terracotta-dark transition-all"
                >
                  {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copiedSql ? "Tersalin!" : "Salin SQL"}
                </button>
              </div>

              <div className="relative rounded-2xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800 leading-relaxed shadow-inner">
                <pre>{sqlSchema}</pre>
              </div>
            </div>
          )}

        </div>

        {/* Footer */}
        <div className="p-4 bg-warm-cream/40 border-t border-outline-variant/15 flex items-center justify-between text-xs text-espresso-dark/70">
          <span className="flex items-center gap-1.5 font-medium">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            Integrasi Otomatis Stock & Midtrans Checkout
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-espresso-dark text-white font-semibold hover:bg-espresso transition-colors"
          >
            Tutup
          </button>
        </div>
      </>
    )}

      </div>
    </div>
  );
};
